/**
* The MIT License (MIT)
*
* Igor Zinken 2019-2021 - https://www.igorski.nl
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of
* this software and associated documentation files (the "Software"), to deal in
* the Software without restriction, including without limitation the rights to
* use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
* the Software, and to permit persons to whom the Software is furnished to do so,
* subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
* FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
* COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
* IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
* CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
<template>
    <div class="loader">
        <div v-if="show" class="uil-default-css">
            <div class="loader__element" style="transform:rotate(0deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(30deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(60deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(90deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(120deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(150deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(180deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(210deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(240deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(270deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(300deg) translate(0,-60px);"></div>
            <div class="loader__element" style="transform:rotate(330deg) translate(0,-60px);"></div>
        </div>
    </div>
</template>

<script lang="ts">
// delay in milliseconds before we show ourselves
// this to prevent flickering animations when loading completes fast enough
const DELAY = 250;

export default {
    data: () => ({
        show: false,
    }),
    created(): void {
        this.to = window.setTimeout(() => {
            this.show = true;
        }, DELAY );
    },
    beforeUnmount(): void {
        window.clearTimeout( this.to );
    },
};
</script>

<style lang="scss" scoped>
@use "sass:math";

@use "@/styles/_colors";
@use "@/styles/_variables";

$loaderSize: 225px;

.loader {
    position: fixed;
    background: #000;
    top: 50%;
    left: 50%;
    width: $loaderSize;
    height: $loaderSize;
    margin-left: math.div( -$loaderSize, 2 );
    margin-top: math.div( -$loaderSize, 2 );
    border-bottom: variables.$spacing-medium solid colors.$color-editor-background;
    transform: scale(0.33);
    z-index: variables.$z-loader;

    &__element {
        position: absolute;
        top: 94px;
        left: 105px;
        width: 14px;
        height: 40px;
        background: #FFE23D;
        border-radius: 14px;
    }
}

/* generated by loading.io */

@-webkit-keyframes uil-default-anim {
    0% {
        opacity: 1;
    }
    100% {
        opacity: 0;
    }
}

@keyframes uil-default-anim {
    0% {
        opacity: 1;
    }
    100% {
        opacity: 0;
    }
}

.uil-default-css > div:nth-of-type(1) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: -0.5s;
    animation-delay: -0.5s;
}

.uil-default-css {
    position: relative;
    width: $loaderSize;
    height: $loaderSize;
    transform:scale(0.75);
}

.uil-default-css > div:nth-of-type(2) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: -0.4166666666666667s;
    animation-delay: -0.4166666666666667s;
}

.uil-default-css > div:nth-of-type(3) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: -0.33333333333333337s;
    animation-delay: -0.33333333333333337s;
}

.uil-default-css > div:nth-of-type(4) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: -0.25s;
    animation-delay: -0.25s;
}

.uil-default-css > div:nth-of-type(5) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: -0.16666666666666669s;
    animation-delay: -0.16666666666666669s;
}

.uil-default-css > div:nth-of-type(6) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: -0.08333333333333331s;
    animation-delay: -0.08333333333333331s;
}

.uil-default-css > div:nth-of-type(7) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: 0s;
    animation-delay: 0s;
}

.uil-default-css > div:nth-of-type(8) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: 0.08333333333333337s;
    animation-delay: 0.08333333333333337s;
}

.uil-default-css > div:nth-of-type(9) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: 0.16666666666666663s;
    animation-delay: 0.16666666666666663s;
}

.uil-default-css > div:nth-of-type(10) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: 0.25s;
    animation-delay: 0.25s;
}

.uil-default-css > div:nth-of-type(11) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: 0.33333333333333337s;
    animation-delay: 0.33333333333333337s;
}

.uil-default-css > div:nth-of-type(12) {
    -webkit-animation: uil-default-anim 1s linear infinite;
    animation: uil-default-anim 1s linear infinite;
    -webkit-animation-delay: 0.41666666666666663s;
    animation-delay: 0.41666666666666663s;
}
</style>
